# Generated by Django 2.1.7 on 2019-03-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190309_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('turn', 'Turn'), ('underway', 'В работе'), ('done', 'Сделано')], default='turn', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_planned',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
