# Generated by Django 2.1.7 on 2019-03-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190309_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('turn', 'Очередь'), ('underway', 'В работе'), ('done', 'Сделано')], default='turn', max_length=20),
        ),
    ]
